# -*- coding: utf-8 -*-
{

    'name': 'GoMart Point Of Sale Management',
    "summary": "GoMart Point Of Sale",
    'version': '10.0.1.0.1',
    'author': "Bista Solutions",
    'category': 'Plan Module',
    'depends': ['point_of_sale',
                'mint_pos',
                'mint_pos_multi_barcode',
                'mint_pos_receipt',
                'point_of_sale_logo',
                'pos_category_pagination',
                'pos_sale_report',
                'product_return_pos',
                'gomart_theme',
                'mint_barcode_label_printing',
                'mint_pos_multi_barcode',
                'stock_zero_qty',
                'mint_client_multi_store',
                'import_product_image',
                'partner_credit_limit',
                'product_multi_images',
    ],
    "website": "https://www.bistasolutions.com",
    "data": [ ],
    "demo": [ ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
